const publicAsset = (name: string) => `${import.meta.env.BASE_URL}images/${name}`;
export const resume = `${import.meta.env.BASE_URL}resume.pdf`;
export const PROJECTS = [
  { title: 'CivicHub', category: 'Community platform', tags: ['Product', 'Backend'], description: 'A community issue reporting app that connects a mobile-first experience to a real backend with auth, media uploads, and local persistence.', stack: ['Expo', 'Express', 'SQLite', 'JWT'], link: 'https://github.com/satyamverma21/CivicHub', image: publicAsset('civichub.png') },
  { title: 'Enterprise RAG Knowledge Base', category: 'AI system', tags: ['AI', 'Backend'], description: 'A grounded knowledge assistant designed around a frontend/backend split for reliable enterprise retrieval and responses.', stack: ['RAG', 'Python', 'LLMs'], link: 'https://github.com/satyamverma21/Enterprise-RAG-Knowledge-Base-Assistant', image: publicAsset('enterprice.png') },
  { title: 'SQL Chatbot', category: 'Natural language interface', tags: ['AI', 'Backend'], description: 'Ask questions in plain English and turn them into useful SQL across SQLite and MySQL databases.', stack: ['LangChain', 'ChatGroq', 'SQL'], link: 'https://github.com/satyamverma21/SQL-Chatbot-demo', image: publicAsset('sqlchatbot.png') },
  { title: 'FloraSense', category: 'Applied ML product', tags: ['Product', 'Backend'], description: 'Plant species identification and disease detection wrapped in a responsive Flask application for early intervention.', stack: ['Flask', 'Plant.id API', 'Tailwind'], link: 'https://github.com/satyamverma21/FloraSense', image: publicAsset('florasense.png') },
  { title: 'Kedarnath Stay Website', category: 'Full-stack web app', tags: ['Product', 'Backend'], description: 'A booking experience with an Angular frontend and Node.js backend for a focused hospitality use case.', stack: ['Angular', 'Node.js', 'JavaScript'], link: 'https://github.com/satyamverma21/Kedarnath-stay-website', image: publicAsset('kedar.png') },
  { title: 'Resume Analyser RAG', category: 'NLP workflow', tags: ['AI'], description: 'A Python document processing workflow that uses retrieval-style analysis to make resume review more useful.', stack: ['Python', 'NLP', 'RAG'], link: 'https://github.com/satyamverma21/Resume_analyzer_RAG', image: publicAsset('resume.png') },
  { title: 'Plant Pal', category: 'Mobile app', tags: ['Product'], description: 'A React Native plant detection app with identification, market, and sell-plant flows.', stack: ['React Native', 'API', 'Mobile'], link: 'https://github.com/satyamverma21/PlantPal', image: publicAsset('plantpal.png') },
];
